apiVersion: apps/v1
kind: Deployment
metadata:
  name: webrtc-signaling
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webrtc-signaling
  template:
    metadata:
      labels:
        app: webrtc-signaling
    spec:
      containers:
      - name: webrtc-signaling
        image: webrtc-signaling:latest
        ports:
        - containerPort: 3000
        env:
        - name: REDIS_HOST
          value: "redis-master"
        - name: REDIS_PORT
          value: "6379"
---
apiVersion: v1
kind: Service
metadata:
  name: webrtc-signaling
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3000
  selector:
    app: webrtc-signaling 